// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDPUu4ccXijUZud3uHJMgHm6vWtW5VZc',
    appId: '1:1076788727813:web:e31022cb9bd2f5f8d84c6c',
    messagingSenderId: '1076788727813',
    projectId: 'another-authentication-b8467',
    authDomain: 'another-authentication-b8467.firebaseapp.com',
    storageBucket: 'another-authentication-b8467.appspot.com',
    measurementId: 'G-8KFQTE9R3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUpSOP-X21OIGGP7GLyMt2pgUEK0gLTE',
    appId: '1:1076788727813:android:87985e68d3e712cfd84c6c',
    messagingSenderId: '1076788727813',
    projectId: 'another-authentication-b8467',
    storageBucket: 'another-authentication-b8467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqgjkaKF-_OJPoJTCIESQEvTZe8tkp9Qc',
    appId: '1:1076788727813:ios:41d1070458a4144ed84c6c',
    messagingSenderId: '1076788727813',
    projectId: 'another-authentication-b8467',
    storageBucket: 'another-authentication-b8467.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqgjkaKF-_OJPoJTCIESQEvTZe8tkp9Qc',
    appId: '1:1076788727813:ios:76e595aa7529a11ed84c6c',
    messagingSenderId: '1076788727813',
    projectId: 'another-authentication-b8467',
    storageBucket: 'another-authentication-b8467.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
